listeners:
  - query_port: 25577
    motd: "&b&lLunaMC &7| &dA Multiverse Adventure &8[&aSurvival&8, &bCreative&8, &cLifeSteal&8]"
    tab_list: GLOBAL_PING
    query_enabled: false
    proxy_protocol: false
    forced_hosts:
      pvp.md-5.net: pvp
    bind_local_address: true
    host: 0.0.0.0:25577
    max_players: 100
    tab_size: 60
    ping_passthrough: false
    force_default_server: true
    priorities:
      - hub
online_mode: false
servers:
  hub:
    motd: "&eHub World"
    address: hub:25565
    restricted: false
  survival:
    motd: "&aSurvival"
    address: survival:25565
    restricted: false
  creative:
    motd: "&bCreative"
    address: creative:25565
    restricted: false
  lifesteal:
    motd: "&cLifeSteal"
    address: lifesteal:25565
    restricted: false
ip_forward: true
network_compression_threshold: 256
disabled_commands:
- disabledcommandhere
timeout: 30000
connection_throttle: 4000
stats: 9d2a72b6-fake-stat-id
